#!/usr/bin/env bash
set -euo pipefail

die() { echo "[verify][err] $*" >&2; exit 2; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

stamp="$(date +%Y%m%d_%H%M%S)"
rand="$(python3 - <<'PYY'
import secrets
print(secrets.token_hex(4))
PYY
)"
run_dir="$ROOT/artifacts/runs/run_generated_smoke_${stamp}_${rand}"
mkdir -p "$run_dir"

latest_run=""
if [[ -f "$ROOT/artifacts/runs/LATEST" ]]; then
  latest_run="$(cat "$ROOT/artifacts/runs/LATEST" | tr -d '\r\n' || true)"
fi

gen_dir="${GEN_DIR:-}"

# 1) GEN_DIR env
# 2) match by .generated_from_run == LATEST
# 3) newest under apps/generated
if [[ -z "$gen_dir" && -n "$latest_run" ]]; then
  match="$(grep -Rsl --fixed-strings "$latest_run" "$ROOT/apps/generated"/*/.generated_from_run 2>/dev/null | head -n 1 || true)"
  if [[ -n "$match" ]]; then
    gen_dir="$(dirname "$match")"
  fi
fi

if [[ -z "$gen_dir" ]]; then
  gen_dir="$(ls -1dt "$ROOT/apps/generated"/* 2>/dev/null | head -n 1 || true)"
fi

[[ -n "$gen_dir" ]] || die "cannot resolve gen_dir. Set GEN_DIR=/abs/path/to/apps/generated/<name>"

echo "[verify] run_dir=$run_dir"
echo "[verify] gen_dir=$gen_dir"
echo "[verify] ts=$(date -Iseconds)" | tee "$run_dir/verify.log"

# Try to infer package name/import name from pyproject.toml
PKG_NAME="$(python3 - <<'PYY'
import re
from pathlib import Path

p = Path("pyproject.toml")
if not p.exists():
    print("")
    raise SystemExit(0)

txt = p.read_text(encoding="utf-8", errors="ignore")

m = re.search(r'(?m)^\s*name\s*=\s*["\']([^"\']+)["\']\s*$', txt)
print(m.group(1) if m else "")
PYY
)"

cd "$gen_dir" || die "cannot cd to gen_dir=$gen_dir"

# If pyproject declares readme=README.md but README missing, create a stub to avoid hatchling error
python3 - <<'PYY'
from pathlib import Path
import re

pp = Path("pyproject.toml")
if not pp.exists():
    raise SystemExit(0)

txt = pp.read_text(encoding="utf-8", errors="ignore")
needs = bool(re.search(r'(?m)^\s*readme\s*=\s*["\']README\.md["\']\s*$', txt))
if needs and not Path("README.md").exists():
    Path("README.md").write_text("# Generated Project\n\nAutogenerated by ai-platform.\n", encoding="utf-8")
    print("[fix] created README.md (required by pyproject)")
PYY

# Ensure python -m <pkg> works if src layout exists
python3 - <<'PYY'
from pathlib import Path

src = Path("src")
if not src.exists():
    raise SystemExit(0)

pkgs = [p for p in src.iterdir() if p.is_dir() and (p / "__init__.py").exists()]
if not pkgs:
    raise SystemExit(0)

pkg = pkgs[0].name
main = src / pkg / "__main__.py"
if not main.exists():
    main.write_text(
        "from .cli import main\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    print(f"[fix] created src/{pkg}/__main__.py to support: python -m {pkg}")
PYY

python3 -V | tee -a "$run_dir/verify.log"
python3 -m pip -V | tee -a "$run_dir/verify.log"

# Create isolated venv for verification
python3 -m venv .venv_verify
source .venv_verify/bin/activate
python -m pip install -U pip >/dev/null

# Editable install + basic smoke
python -m pip install -e . | tee -a "$run_dir/verify.log"

# Try CLI help if console script exists
if [[ -n "${PKG_NAME:-}" ]]; then
  echo "[run] ${PKG_NAME} --help" | tee -a "$run_dir/verify.log"
  "${PKG_NAME}" --help | sed -n '1,80p' | tee -a "$run_dir/verify.log" || true
fi

# Try python -m <import> --help based on src package name
python - <<'PYY' | tee -a "$run_dir/verify.log"
from pathlib import Path
src = Path("src")
pkgs = [p for p in src.iterdir() if p.is_dir() and (p / "__init__.py").exists()] if src.exists() else []
if pkgs:
    print("[info] import_candidate=", pkgs[0].name)
else:
    print("[info] no src package detected")
PYY

echo "[ok] generated project smoke test passed" | tee -a "$run_dir/verify.log"
